# Generated by Django 4.2.1 on 2023-05-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='mypage/static/mypage/img/user_photos/'),
        ),
    ]
